### ISSUE TITLE
What is the current progress

### ISSUE THREAD

**Issue by paulyang1990** [Le0nX/ModernRoboticsCpp#1]
Hi Le0nX, 

I was using Modern Robotics Matlab package recently and thinking of writing my own C++ version but I found your implementation and saw your discussion with stevenjj. Thanks for doing this effort.  I want to contribute as well. I would like to know what is your current progress? I folked this repo and will do some testing soon to make it more complete. If you are working on improving the current repo, could you share your currrent progress and development plan?

**Comment by Le0nX** [comment]
Hi @paulyang1990! 

Thanks for your interest. I've currently stopped developing the library due to tight work schedule. But I'm ready to continue the development process next week. The plan is very simple: i just take functions from the [list](https://github.com/NxRLab/ModernRobotics/blob/master/packages/Python/modern_robotics/core.py) and implement them :)

**Comment by Le0nX** [comment]
@paulyang1990 I've created project's [board](https://github.com/Le0nX/ModernRoboticsCpp/projects/1) with the list of functions to be implemented. You can take any function you want and tell me, i'll mark it "in progress" stage and nobody will duplicate it.

**Comment by paulyang1990** [comment]
Hi @Le0nX, excellent plan. 
Please have a look at: 
https://github.com/paulyang1990/ModernRoboticsCpp/blob/master/src/lib_test.cpp

I added google test framework to my forked code and add **JacobianSpace.** Also I created a namespace for modern robotics functions called "mr". If you think these are appropriate features, I will continue in this direction and submit PR to your repo.

**Comment by paulyang1990** [comment]
Sorry, I added JacobianBody instead of JacobianSpace. But I created test cases for both of them.

**Comment by Le0nX** [comment]
@paulyang1990, Sounds really great!  We look forward to seeing your pull-request!
