### ISSUE TITLE
Please initialize your matrix properly

### ISSUE THREAD

**Issue by paulyang1990** [Le0nX/ModernRoboticsCpp#15]
I submitted a pr to master about adding inverseDynamics.

During the implementation of this function, I experience some numerical problems, I have to stay up until 1:00am to debug. I found them come from TransInv, I need to modifiy it in the following way:

![2](https://user-images.githubusercontent.com/816645/53282570-7d6b6600-3707-11e9-931e-fdeff7b5c6be.PNG)

Eigen does not initiate matrixXd to be all zero values. You have to manual initialize them otherwise they will keep random values that can cause numerical issues.

Please initialize your matrix properly, thanks.

**Comment by Le0nX** [comment]
I'll leave it here opened for other contributors

**Comment by sunoval2016** [comment]
I had the exact issue; LOL. Fixed it in a new pull request

**Comment by paulyang1990** [comment]
@sunoval2016  check other people's commit before commit yours. I fixed it. You don't need to fix it again. 
You new pr does not make any sense.

I am sorry if I sounds like an ass but it was your code made me stay up and many of your previous commits are not professional. Please use Github properly and test your code properly.

**Comment by sunoval2016** [comment]
> 
> 
> @sunoval2016 check other people's commit before commit yours. I fixed it. You don't need to fix it again.
> You new pr does not make any sense.
> 
> I am sorry if I sounds like an ass but it was your code made me stay up and many of your previous commits are not professional. Please use Github properly and test your code properly.

@paulyang1990, I went through the exact same debug process as you and fixed it. I don't think the uninitialized bug code is from me either. Thanks.

**Comment by paulyang1990** [comment]
I am sorry. I checked commit log, it was ipa who implemented TransInv. 

Apologize for my comment on you.

But your commits do need improvements.

**Comment by sunoval2016** [comment]
Hi @paulyang1990, definitely. Learned a lot from you guys already. Looking forward to work more with you. Thanks
