### ISSUE TITLE
Will continue to work on functions related to inverse dynamics

### ISSUE THREAD

**Issue by paulyang1990** [Le0nX/ModernRoboticsCpp#17]
Namely:
MassMatrix
VelQuadraticForces
GravityForces
EndEffectorForces

**Comment by Le0nX** [comment]
Placed your list into "In progress" bar. 
https://github.com/Le0nX/ModernRoboticsCpp/projects/1

**Comment by paulyang1990** [comment]
and also ForwardDynamics

pr submitted
